### ISSUE TITLE
Unauthenticated API calls does seem to work anymore with osc-cli 1.7.1

### ISSUE THREAD

**Issue by garnierclement** [outscale/osc-cli#172]
Hello,
Given an empty profile without AK/SK but only region defined (see example below).
```
    "noauth-euw2" : {
        "access_key": "",
        "secret_key": "",
        "host": "outscale.com",
        "https": true,
        "method": "POST",
        "region_name": "eu-west-2"
    }
```
Using osc-cli 1.6.0, API calls as mentioned below work fine 👍 
`osc-cli --profile noauth-euw2 icu ReadPublicCatalog`
`osc-cli --profile noauth-euw2 api ReadRegions`

Using osc-cli 1.7.1, the following error is displayed and even if those calls should be not identified, CLI does not work anymore and request AK/SK.
`RuntimeError: Secret key is needed to authorize call`

**Comment by jerome-jutteau** [comment]
Outscale API calls which do not require authentication:
- ReadFlexibleGpuCatalog
- ReadLocations
- ReadNetAccessPointServices
- ReadProductTypes
- ReadPublicIpRanges
- ReadRegions
- ReadVmTypes
- ResetAccountPassword
- SendResetPasswordEmail

ICU calls which do not require authentication:
- AuthenticateAccount (kind of)
- ResetAccountPassword
- SendResetPasswordEmail
- ReadPublicCatalog
- CheckSignature

FCU calls which do not require authentication:
- DescribeRegions
- ReadPublicIpRanges

LBU, EIM and Directlink: al calls require authentication

**Comment by jerome-jutteau** [comment]
Issue should now be solved. Note that you should not need a specific empty profile for calls which do not need authentication. New release is coming soon.
