### ISSUE TITLE
OAPI support

### ISSUE THREAD

**Issue by jerome-jutteau** [outscale/osc-cli#6]
Hi !

Now that Outscale has OAPI support, we need it in osc-cli.
Also, OAPI is the default API to be used so osc-cli user may be specify any service and use OAPI.

Thanks !

**Comment by outscale-jju** [comment]
Why OKMS support implementation would close this issue ?

**Comment by outscale-frl** [comment]
> Why OKMS support implementation would close this issue ?

Don't know why it has been decided to resolve this one into the #8. I didn't see it :/
